import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import ToastWrapper from "./_components/toast-wrapper";
import QueryWrapper from "./_components/query-wrapper";
import NextTopLoader from "nextjs-toploader";
// import ReactScan from "./_components/react-scan";
const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} antialiased`}>
				<NextTopLoader color="var(--color-secondary)" />
				{/* <ReactScan /> */}
				<QueryWrapper>
					{children}
					<ToastWrapper />
				</QueryWrapper>
			</body>
		</html>
	);
}
